#!/usr/bin/bash
#
# Author: paraxic <paraxic@outlook.com>
# Version: 1.10
# Date:    09/10/2018
# Updated: 09/19/2018
# Desc: The [m]odular [b]ash [l]emonbar panel

# config
FG_COLOR=ffffff
BG_COLOR='222222'
WIFI_DEV="wlp2s0"
bat_good="00ff00"
bat_alert="ffff00"
bat_term="ff0000"
#unused
#HI_COLOR=
IP_COLOR=ffcc00
CDESK_COLOR=ccff00
#unused
#DATE_COLOR=
#unused
#TIME_COLOR=

# mbl panel "Main"

#load modules
source ./lib/battery
source ./lib/common
source ./lib/clock
source ./lib/bspwm
source ./lib/net

#preloop functions

get_desk_by_name

#main loop 

while true; do
	get_current_desktop
	#set_color bg $BG_COLOR
	echo -n "%{l}"
	print_desk_v2
	color_reset 
	echo -n "%{c}"
	print_ssid $WIFI_DEV $IP_COLOR
	echo -n " @ "
	print_ip $IP_COLOR
	echo -n "%{r}"
	get_battery_charge
	print_bat
	color_reset
	clock
	color_reset 
	echo
	sleep 1
done
