#!/bin/bash
#
# Author: paraxic <paraxic@outlook.com>
# Version: 1.11
# Date:   09/30/18
# Updated: 10/15/18
# Desc: Retrieve battery status
BAT_PER=
BAT_CHG=
source ./lib/common
function get_battery_charge(){
 BAT_PER=$(acpi | sed -e "s/^.*g, //" -e "s/%, .*//")
 BAT_CHG=$(acpi | sed -re "s/Battery 0: (.+)/\1/" -e 's/,.*//')
}

function print_bat(){
	if [[ $BAT_CHG != "Charging" ]]
	then
	    echo -n "Bat[D]: "
	else
		if [[ $BAT_CHG == "Charging" ]]
		then
		    echo -n "Bat[C]: "
		fi
	fi
	if [[ $(expr "$BAT_PER" ">" 50) == 1 ]]
	then
		hilight "fg" "$bat_good" "$BAT_PER% "
	else
	 if [[ $(expr "$BAT_PER" "<=" 50) == 1 && $(expr "$BAT_PER" ">" 25) == 1 ]]
	 then
		hilight "fg" "$bat_alert" "$BAT_PER% "
	 fi
	 if [[ $(expr "$BAT_PER" "<=" 25) == 1 ]]
	 then
	 	hilight "fg" "$bat_term" "$BAT_PER% "
	 fi
	fi
	
}
